### ISSUE TITLE
Add `test` method that mocks environment, like unblock

### ISSUE THREAD

**Issue by dan335** [meteor/validated-method#11]
```
method = new ValidatedMethod({
  name: 'method',
  validate: null,
  run() {
    this.unblock();
  }
});
```

this works

```
method.call();
```

this

```
method._execute();
```

gives me this error

```
TypeError: Object [object global] has no method 'unblock'
```

**Comment by stubailo** [comment]
I think it might make sense to add a special function called `test` or something that automatically passes nice default stubs for things, and just isn't run when the Method is called for real.

The way it works now, `_execute` is the internal function that runs when the Method is actually called in the real app, so it probably wouldn't make sense to add functionality inside to pass fake versions of `unblock` and such.

**Comment by dan335** [comment]
Sounds like a good idea to me.

**Comment by stubailo** [comment]
This could now be implemented via mixin:

https://github.com/meteor/validated-method#mixins

**Comment by diavrank** [comment]
Hello, I have the same problem [here](https://github.com/meteor/meteor/issues/11561#issue-955267442). Any suggestions to solve it?

**Comment by filipenevola** [comment]
Hi @diavrank did you try via mixin as suggested by Sashko?

**Comment by diavrank** [comment]
@filipenevola I read the section of mixins that Sashko shared, however, I have no idea which mixin I have to add, in order to solve the problem.

**Comment by filipenevola** [comment]
Hi @diavrank I didn't test but as far as I understand he means that you could create a mock unblock function using a mixin.

I'm writing the following code directly on GitHub so maybe it doesn't work :)

```js
export const unblockMixin = options => {
  const { run } = options;

  return assign(options, {
    run(...args) {
      if (Meteor.isTest) {
        this.unblock = () => {}; // no-op
      }
      return run.call(this, ...args);
    },
  });
};
```

And you could use like this in your code:
```js
new ValidatedMethod({
  name: 'yourMethod',
  mixins: [unblockMixin],
  validate: null, // your validation
  run(args) {
    this.unblock(); // It would always exists
    // your method body
  },
});
```

Let me know if this works.

**Comment by diavrank** [comment]
Thank you @filipenevola ,it did work. I used this code with TS:

_unblockOnTest.ts_
```ts
import { Meteor } from 'meteor/meteor';

export const unblockOnTest = (options: any) => {
	const { run } = options;

	return Object.assign(options, {
		run(...args: any[]) {
			if (Meteor.isTest || Meteor.isAppTest) {
				this.unblock = () => {
				}; // no-op
			}
			return run.call(this, ...args);
		}
	});
};

```
