### ISSUE TITLE
Unable to call a server only validated method from the client

### ISSUE THREAD

**Issue by elie222** [meteor/validated-method#13]
If you have a method `Posts.methods.someServerOnlyMethod = new ValidatedMethod({...})` that is only defined on the server, you can't call this from the client using `Posts.methods.someServerOnlyMethod.call()` or it will throw an `undefined` error, instead you have to do `Meteor.call('Posts.methods.someServerOnlyMethod')` to call it.

Perhaps this is obvious, but this is another difference between regular Methods and Validated Methods.

**Comment by stubailo** [comment]
Yes, if you wanted to have some server-only code you could do it one of two ways:
1. Define the method using `ValidatedMethod` and then call it with `Meteor.call` (but then you don't get some of the benefits of the package, although there are still some advantages)
2. Define the method on client and server, but factor out the server-side logic into a function on the server: http://guide.meteor.com/security.html#served-files

**Comment by tzapu** [comment]
@stubailo sorry for commenting on such an old issue, but could you please elaborate on
"Define the method using ValidatedMethod and then call it with Meteor.call (but then you don't get some of the benefits of the package, although there are still some advantages)"

What is missing when run through meteror.call? Does validation still run? mixins?

Cheers

**Comment by elie222** [comment]
With meteor.call you're calling functions through strings. With validated
method you're not. It's an actual object with that name.
On 6 Jul 2016 16:00, "tzapu" notifications@github.com wrote:

@stubailo https://github.com/stubailo sorry for commenting on such an old
issue, but could you please elaborate on

"Define the method using ValidatedMethod and then call it with Meteor.call
(but then you don't get some of the benefits of the package, although there
are still some advantages)"

What is missing when run through meteror.call? Does validation still run?
mixins?

Cheers

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
https://github.com/meteor/validated-method/issues/13#issuecomment-230763888,
or mute the thread
https://github.com/notifications/unsubscribe/AC8oX8n3DNe0pjlnz_IWHZdoQ04PilH4ks5qS6bfgaJpZM4GviJv
.

**Comment by tzapu** [comment]
hi, sorry to insist, but would all the contents of the method call still run when ran through Meteor.call ?

especially validation, would that be affected if a validated method is called through Meteor.call as a string?

thanks

**Comment by elie222** [comment]
Yes. It should all run the same.
