### ISSUE TITLE
Before and After Hooks

### ISSUE THREAD

**Issue by JonathanHindi** [meteor/validated-method#27]
I am really interested in the approach that this package provide and I see that it could replace all the Method definitions wrapper we were writing. I would also suggest if this package have the option to pass before hooks and after hooks as an array of functions that would be great. 

Suggested API: 

``` js
const loadData = function (args) {
  // e.g load data hook that tries to load the data and if failed do something maybe throw a 404.
};

const method = new ValidatedMethod({
  name: 'methodName',
  before: [
    LoadData
  ],
  after: [

  ]
});
```

It's simply what [Method Hooks](https://github.com/Workpop/meteor-method-hooks) does, however in a more readable way.

**Comment by stubailo** [comment]
It's very easy to do with a mixin - I'll give you example code here, but I don't want to write and maintain the package so please feel free to do so.

Code:

``` js
HookMixin = function HookMixin(options) {
  const oldRun = options.run;

  const beforeCallbacks = options.before;
  const afterCallbacks = options.after;

  check(beforeCallbacks, [Function]);
  check(afterCallbacks, [Function]);

  const newRun = function hookedRun(args) {
    beforeCallbacks.forEach(callback => callback(args));
    const returnValue = oldRun(args);
    afterCallbacks.forEach(callback => callback(args));
    return returnValue;
  }

  options.run = newRun;

  return options;
}
```

It's up to you what arguments you want to pass to the hooks - for example you might want to pass the method name, and possibly let the after hooks override the return value, so that they can act as middleware.

**Comment by stubailo** [comment]
You would use the mixin like this:

``` js
const method = new ValidatedMethod({
  name: 'methodName',
  mixins: [HookMixin],
  before: [
    LoadData
  ],
  after: [

  ]
});
```

Let me know if you make and publish a package, and I'll add it to this package's README.

**Comment by stubailo** [comment]
Also, keep in mind that you might want some of the hooks to run only on the client or the server - in the above example they would all execute on both.

**Comment by leonidez** [comment]
@stubailo Using your tips I've created a mixin for before/after method hooks. Here's the project on Github and Atmosphere:

https://github.com/leonidez/method-hooks
https://atmospherejs.com/lacosta/method-hooks

If you have any opinions/preference please let me know.

**Comment by stubailo** [comment]
@leonidez is the before hook allowed to change the arguments before they are passed to the method? Is the after hook allowed to change the return value?

**Comment by stubailo** [comment]
(It's OK if not, just curious! we can list it in the README either way if you send a PR to this section: https://github.com/meteor/validated-method#community-mixins

**Comment by leonidez** [comment]
No to both. The before hook receives the method arguments and the options object. The after hooks receive the method arguments, the method's return value, and the options object. I'll submit a PR, and I'll add issues to my own repo so I can include that functionality. Thanks!

**Comment by stubailo** [comment]
Well now there is a mixin! Closing the issue.

**Comment by aessig** [comment]
@stubailo Hi, how can I make the hook only execute on the server ? More generally, how can I not run a validated method on the client ?
