### ISSUE TITLE
TinyTest passing in Chrome but not in Mozilla.

### ISSUE THREAD

**Issue by ghost** [meteor/validated-method#28]
Hi guys, 

I've been playing with the package but didn't have great success unfortunately :(
For instance, I defined a super simple method, and wanted to test the validation of the method and I found that the test is passing in Chrome but not in mozilla.

---

Method definition:

MailSystem.methods.sendUserContact = new ValidatedMethod({

   name: 'MailSystem.methods.sendUserContact',

   validate: new SimpleSchema({
      name: {type: String, min: 2, max: 50},
      email: {type: String, regEx: SimpleSchema.RegEx.Email, min: 5, max: 50},
      message: {type: String, min: 2, max: 2000}
   }).validator({clean: true}), // SEE: v1.5 at https://github.com/aldeed/meteor-simple-schema/blob/

   run({name, email, message}) {
         // DO NOTHING
   }
});

---

Test:

Tinytest.addAsync('Both - Does MailSystem.methods.sendUserContact fail on empty name?', function(test, next) {
      var data = {
         name: '',
         email: 'example@gmail.com',
         message: 'hola hola'
      };
      MailSystem.methods.sendUserContact.call(data, function(err) {
         console.log('err: ', err);  
         test.isNotUndefined(err, 'err is undefined');
         test.isNotUndefined(err.error, 'err.error is undefined');  
         next();
      });
   });

---

Chrome passes both tests in client and server.
Chrome console:
err:  _class {error: "validation-error", reason: "Name is required", details: Array[1], message: "Name is required [validation-error]", errorType: "Meteor.Error"}details: Array[1]error: "validation-error"errorType: "Meteor.Error"message: "Name is required [validation-error]"reason: "Name is required"stack: (...)get stack: ()set stack: ()__proto__: _class

---

Mozilla passes both tests on server, but not on the client.
Mozilla console:
err:  Object { stack: "" }

---

Server console:
err:  { [Error: Name is required [validation-error]]
I20160116-18:15:55.167(1)?   error: 'validation-error',
I20160116-18:15:55.167(1)?   reason: 'Name is required',
I20160116-18:15:55.167(1)?   details: [ { name: 'name', type: 'required', details: [Object] } ],
I20160116-18:15:55.167(1)?   message: 'Name is required [validation-error]',
I20160116-18:15:55.168(1)?   errorType: 'Meteor.Error' }

---

Package on use:
   var coreDep = [
      'meteor-base',
      'mongo',
      'spacebars',
      'accounts-facebook',
      'accounts-google',
      'accounts-meteor-developer',
      'accounts-password',
      'accounts-twitter',
      'accounts-ui',
      'audit-argument-checks',
      'blaze-html-templates',
      'browser-policy',
      'check',
      'ecmascript',
      'ejson',
      'email',
      'jquery',
      'logging',
      'mobile-experience',
      'random',
      'reactive-dict',
      'reactive-var',
      'ddp-rate-limiter',
      'reload',
      'service-configuration',
      'session',
      'standard-minifiers',
      'tracker'
   ];
   // Third-party packages
   var extDep = [
      'iron:router@1.0.12',
      'aldeed:simple-schema@1.5.3',
      'aldeed:collection2@2.8.0',
      'appshore:recaptcha@2.0.6',
      'chrismbeckett:toastr@2.1.2_1',
      'cunneen:mailgun@0.9.1',
      'dburles:mongo-collection-instances@0.3.5',
      'differential:event-hooks@1.5.0',
      'doctorpangloss:method-hooks@2.0.2',
      'fortawesome:fontawesome@4.5.0',
      'fourseven:scss@3.4.1',
      'hashwin:ionicons-sass@0.1.9',
      'gadicohen:headers@0.0.31',
      'liberation:shareit@1.1.1',
      'maibaum:foundation-icons@0.0.1',
      'manuelschoebel:ms-seo@0.4.1',
      'matb33:collection-hooks@0.8.1',
      'mdg:validation-error@0.3.0',
      'mdg:validated-method@1.0.0',
      'meteorhacks:kadira@2.26.3',
      'meteorhacks:sikka@1.0.1',
      'meteorhacks:ssr@2.2.0',
      'mizzao:bootboxjs@4.4.0',
      'mrt:cookies@0.3.0',
      'mrt:moment@2.8.1',
      'nahue:simple-line-icons@1.0.0',
      'natestrauser:animate-css@3.4.0',
      'natestrauser:select2@4.0.0_1',
      'ongoworks:spiderable@1.0.7',
      'outatime:geolib@2.0.15',
      'percolate:synced-cron@1.3.0',
      'plusmore:reactive-responsive-helpers@1.1.0',
      'rajit:bootstrap3-datepicker@1.5.0',
      //'rcy:nouislider@7.0.7_2',
      'reywood:iron-router-ga@0.7.1',
      'reywood:publish-composite@1.4.2',
      'sacha:spin@2.3.1',
      'selaias:meteor-simpleweather@0.6.8',
      'taehee:rand-token@0.0.3',
      'tap:i18n@1.7.0',
      'thebakery:ipgeocoder@0.1.2',
      'twbs:bootstrap@3.3.6',
      'utilities:avatar@0.9.2',
      'vodkabears:vide@0.4.1'
   ];

---

Final remark: I had to add '{clean: true}' inside the validator in order for SimpleSchema to trim the input before doing validation, otherwise empty strings with just 'many white spaces' would pass validation when it shouldn't. I think this should be pointed out at the meteor guide, otherwise it doesn't make sense to set 'min' field on string validation for instance.

Hope I'm not doing any stupid mistake!

Cheers

**Comment by stubailo** [comment]
If possible, could you send a PR to this package with the test above? Then I can work on:
1. Making it pass everywhere
2. Figuring out how to run the tests in multiple browsers in CI

**Comment by ghost** [comment]
Hi @stubailo , 
I've created a repo with the example (I tried to make a pull request but had no luck :( ... still learning): https://github.com/orcprogramming/validated-method-fail-example

Hope it helps!

**Comment by stubailo** [comment]
OK, using the debugger I think I know what happens:

It's a problem with ValidationError extending Meteor.Error - somehow, the error message doesn't make it when the constructor is called. Going to write a simpler test now.

**Comment by stubailo** [comment]
Looks like the basic ValidationError tests don't actually pass in Firefox. We should set up CI to run the tests in all browsers.
