### ISSUE TITLE
TypeScript definitions

### ISSUE THREAD

**Issue by DmitryEfimenko** [meteor/validated-method#30]
I didn't see any TypeScript definitions so I cooked this quickly. Hopefully this can be developed further and added to docs:

``` typescript
/// <reference path="../meteor/meteor.d.ts" />

declare class ValidatedMethod<T> extends MeteorValidatedMethod.ValidatedMethod<T> { }

declare module MeteorValidatedMethod {
    export class ValidatedMethod<T> {
        constructor(options: ValidatedMethodOptions<T>);
        call(options?: T, cb?: (err, res)=> void): void;
    }

    interface ValidatedMethodOptions<T> {
        name: string;
        mixins?: Function[];
        validate: any;
        run(opts: T);
    }
}
```

**Comment by stubailo** [comment]
What's the preferred way to ship typescript definitions? Should they be in the package source code somehow? How can I test that they are correct? Also, does this allow for mixins?

**Comment by DmitryEfimenko** [comment]
There is a Github Repository: [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) where willing people upload definitions if they are missing. I believe definitions need to be maintained manually. Here they write a bit about [requirements and Tests](http://definitelytyped.org/guides/contributing.html) for uploaded definitions.

**Comment by stubailo** [comment]
If you like, you can upload your definition there. Since I don't use typescript myself, I'd need someone who actually uses it frequently to maintain the definition.

**Comment by stubailo** [comment]
I'm going to close this issue since there isn't really an actionable resolution.

**Comment by twastvedt** [comment]
I've added @DmitryEfimenko's typings to a repository here: https://github.com/twastvedt/typed-meteor-validated-method. I'm planning to add to them while I use this in a project, and then link to the registry when it's more complete. Pull requests are welcome, though, to speed up the process!

**Comment by twastvedt** [comment]
Also, since I had to figure this out, thought it was worth adding here: 
You can use the repository for typings in a project, before it gets integrated into the registry, like this:

`"meteor-validated-method": "github:twastvedt/typed-meteor-validated-method"`

**Comment by stubailo** [comment]
@twastvedt to make it easier for people to find in the future, would you mind sending a PR to the README to add directions for typescript?
