### ISSUE TITLE
ValidatedMethod Mixin : logged-in user Mixin check before run functions

### ISSUE THREAD

**Issue by nabiltntn** [meteor/validated-method#31]
A simple Mixin to check if the user is logged in before every run function.
It requires the new `checkLoggedInError` option which includes the required informations to throw an Error.
### Github:

https://github.com/nabiltntn/loggedin-mixin
### Atmosphere:

tunifight:loggedin-mixin : https://atmospherejs.com/tunifight/loggedin-mixin

**Comment by stubailo** [comment]
Looks great! I will link to it in the README. If you want to speed up the process, you can also submit a PR for that.
