### ISSUE TITLE
Add to list of community mixins: RestrictMixin - throw errors on specified conditions before the run function

### ISSUE THREAD

**Issue by ziarno** [meteor/validated-method#35]
Hi, I've created a mixin to prevent too many `if(condition) { throw error}` statements in the `run` method - check it out :)
https://github.com/ziarno7/restrict-mixin

**Comment by stubailo** [comment]
@ziarno7 really awesome! For consistency, can we rename `data` to `args`? It just wasn't clear to me what that argument was based on the code snippet.

Can you send a PR to list your package here? https://github.com/meteor/validated-method#community-mixins

Please include a link to your atmosphere page!

**Comment by ziarno** [comment]
Changed argument name to `args`.

It's actually my first package to be published on atmosphere - it doesn't seem to be there... I did follow the instructions on https://atmospherejs.com/i/publishing, but can't find it on atmosphere. Any idea why that might be?

**Comment by stubailo** [comment]
Hmm, looks like we had some trouble with atmosphere today, so the worker that syncs the package server didn't run today. It should be up by tomorrow.

Note that you can find your package with `meteor search` on the command line. Let's wait until Atmosphere is working again before posting the link.
