### ISSUE TITLE
UserId context not working with collection-hooks

### ISSUE THREAD

**Issue by ghost** [meteor/validated-method#41]
Hello,

I'm using this in connection with a server side router to make an api.  To put it simply, when I make a function,j and set the userId in the context, collection-hooks says the userId is null.  Any idea why these two packages don't work together?

``` javascript
dbcall = new ValidatedMethod({
    name:'dbcall',
    validate(){},
    run (){
        console.log(this.userId)
        Items.insert({_id:"hello"})
    }
});
//later on...
dbcall._execute({
    userId:'ebAnEgsK22m5NAghP'
})
```

**Comment by stubailo** [comment]
Calling methods from the server with `Meteor.userId()` set isn't too easy - you need to do some stuff with `Meteor.bindEnvironment` etc. It's not really specific to this package. See the discussion here: https://github.com/meteor/meteor/issues/6388
