### ISSUE TITLE
noRetry flag in a ValidatedMethod

### ISSUE THREAD

**Issue by namirsab** [meteor/validated-method#47]
Hi!
I wonder if its possible to use the new `noRetry` flag with a `ValidatedMethod`. As far as I can see is only for [Meteor.apply](http://docs.meteor.com/#/full/meteor_apply)

Thanks a lot!

**Comment by stubailo** [comment]
Working on this here: https://github.com/meteor/validated-method/pull/46

**Comment by stubailo** [comment]
You can now pass in any options to Meteor.apply here: https://github.com/meteor/validated-method#options-to-meteorapply

thanks for the report!
