### ISSUE TITLE
This with arrow functions 

### ISSUE THREAD

**Issue by elie222** [meteor/validated-method#5]
Some of the examples use arrow functions, but 'this' won't work properly in the arrow functions. For example this.userId won't work in the arrow function. 

The examples with arrow functions are therefore misleading and should be removed IMO, even if they don't actually make use of 'this'. 

Unless I'm mistaken about how arrow functions work.

**Comment by stubailo** [comment]
I can't find the examples you're referring to. We use arrow functions for the method callback, but we always use method shorthand for the `run` method which is where you would use `this.userId`.

**Comment by stubailo** [comment]
Going to close this for now, since I don't think this is actually an issue.
