### ISSUE TITLE
Method#_execute doesn't accept a callback

### ISSUE THREAD

**Issue by johanbrook** [meteor/validated-method#52]
Hi!

It looks like `method#_execute` doesn't accept a callback, like `method#call` does. Is this by design?

My use case is in testing, where I need to wait for work to be finished in the method before asserting:

``` js
it('should create a new project', function(done) {
    Projects.methods.create._execute({userId: Random.id()}, Factory.build('project', {
       teamId: 'foo'
     }), (err, id) => {
      assert.ok(id);
      assert.deepEqual(Projects.findOne(id), {
        name: 'My Project',
        sortOrder: 1,
        teamId: 'foo'
      });

      done();
   });
});
```

**Comment by stubailo** [comment]
It runs syncronously in a fiber, right? So can't you just do:

``` js
    const id = Projects.methods.create._execute({userId: Random.id()}, Factory.build('project', {
       teamId: 'foo'
     });

      assert.ok(id);
      assert.deepEqual(Projects.findOne(id), {
        name: 'My Project',
        sortOrder: 1,
        teamId: 'foo'
      });
```

**Comment by stubailo** [comment]
Let me know if the above doesn't work and we can investigate further.

**Comment by johanbrook** [comment]
Okay, I went to the bottom with it, and it was test code who was at fault. It silently failed, and thus didn't insert stuff in the database, and thus this returned `undefined`, even though it was running with Fibers/async.

So feel free to close if you feel there's no need for a callback to this. I just thought it would be nice to mimic the API for `call()`.

**Comment by stubailo** [comment]
I don't think it makes sense because `call` only has a callback because it gets called asynchronously across the network. Glad your issue got figured out!

**Comment by johanbrook** [comment]
👌 Thanks for the quick reply!
