### ISSUE TITLE
Validator allows empty strings in required fields

### ISSUE THREAD

**Issue by mjesuele** [meteor/validated-method#60]
Hey hey, love this package, so thanks!

I'm getting a bit of a strange problem. I have this method:

``` javascript
const createCourse = new ValidatedMethod({
  name: 'courses.create',
  validate: new SimpleSchema({
    courseCode: { type: String },
    department: { type: String },
    endDate: { type: Date },
    name: { type: String },
    public: { type: Boolean, defaultValue: true, optional: true },
    schoolId: { type: String, label: 'School' },
    startDate: { type: Date },
  }).validator(),
  run(params) {
    if (!this.userId) {
      throw new Meteor.Error('unauthorized', 'You must be logged in to add a new course!');
    }

    return addCourse({
      ...params,
      contactEmail: Meteor.users.findOne(this.userId).email(),
      instructorIds: [this.userId],
      shortcode: shortcode(),
    });
  },
});
```

which is getting called from a form with empty strings as the default values, except for `startDate` and `endDate`, which are initialized to `null`. The referenced Courses collection has a schema attached via Collection2 with the same values for the keys listed above.

If I submit the form without values for `startDate` and `endDate`, I get a validation error from the method. Cool.

But if I fill in values for those two and submit the form with one or more empty strings for the other fields, the method's validator passes and it attempts to insert the document, which fails due to the empty strings.

Any idea why empty strings are passing `{ type: String }` validations in the method, but failing the very same definition in the collection schema?

Thanks!

**Comment by mjesuele** [comment]
Actually, I'm pretty sure I know why it's happening. Collection2 calls `schema.clean(params)` before validating, and that doesn't happen here. Tested this in the console:

``` javascript
import { SimpleSchema } from 'meteor/aldeed:simple-schema';
const schema = new SimpleSchema({ foo: { type: String } });
schema.validator()({ foo: '' }); // no error
schema.clean({ foo: '' }); // returns {}
schema.validator()({}); // validation error: 'Foo is required'
```

Is this desired behavior for ValidatedMethod? I would think that empty strings should fail a `{ type: String }` check.

In the meantime, this is getting me what I want:

``` javascript
  validate(params) {
    const schema = new SimpleSchema({
      courseCode: { type: String },
      department: { type: String },
      endDate: { type: Date },
      name: { type: String },
      public: { type: Boolean, defaultValue: true },
      schoolId: { type: String, label: 'School' },
      startDate: { type: Date },
    });
    return schema.validator()(schema.clean(params));
  },
```

EDIT: Just noticed I can also do this:

``` javascript
.validator({ clean: true });
```

so maybe this behavior is fine after all, but perhaps this belongs in the docs.

**Comment by stubailo** [comment]
Mind submitting a PR to the docs?

**Comment by mjesuele** [comment]
@stubailo Done!
