### ISSUE TITLE
Upsert validation with DenyUpdate

### ISSUE THREAD

**Issue by pcmaffey** [meteor/validated-method#62]
When using Upsert to insert a new record into collection with fieldNam: { DenyUpdate: true }, getting error message: Error: [fieldName] cannot be set during an update(…)

Not a huge issue, can use insert & update instead... Just fyi.

**Comment by stubailo** [comment]
I don't understand what upsert has to do with this package - can you give me more information about why this is a problem in ValidatedMethod?

**Comment by pcmaffey** [comment]
It seems ValidatedMethod is checking the denyUpdate schema field when inserting a new record via upsert. So I can't insert a record with upsert if denyUpdate is true.

**Comment by stubailo** [comment]
That sounds entirely like a simple schema/collection2 issue, since ValidatedMethod never does anything related to how collections or upsert work.

**Comment by pcmaffey** [comment]
Ah right, I put this in the wrong place.
