### ISSUE TITLE
err = TypeError: Cannot read property 'status' of undefined at run (http://localhost:3000/app/app

### ISSUE THREAD

**Issue by itayb8** [meteor/validated-method#63]
Calling a method once a user linked to the app from an email 
Hello,
Part of my app is sending emails to users and non users, with link to the app. 
I have a method which I want to call once the user enters the app. 
I'm having a strange problem the method is sometimes called but most of the time not. 
I'm getting an error-  cant read property 'status' of undefined. 
I tried to call the method after checking Meteor.status() is connected but it didnt help. 
I'll be glad if someone could advise me with where would it be the best to call the method from.
and why i'm getting this error
`import ComponentContainer from "../../../../common/react-meteor/ComponentContainer"; 
import {FlowRouter} from "meteor/kadira:flow-router"; 
import StatusResponsePage from "./StatusResponsePage";
 import {UpdateStatus} from "../../api/methods/UpdateStatus";  

export default class StatusResponsePageContainer extends ComponentContainer<{},   
{   
   isUpdated?:boolean;   
   isMethodCalled?:boolean;   
}> {    

constructor(props) {   
   super(props);   
   this.state = {   
      isUpdated: false,   
     isMethodCalled: false   
   };   
}    

getComponent():any {   
   return StatusResponsePage;   
}    

getMeteorData():Object {   
   const meteorStatus:any = Meteor.status();   
   const changedById = FlowRouter.getQueryParam('changedById');   
   const currentStatus = FlowRouter.getQueryParam('currentStatus');   
   const response = FlowRouter.getQueryParam('response');   
   if(meteorStatus.connected && !this.state.isMethodCalled) {   
      this.setState({isMethodCalled: true});   
      UpdateStatus.call({changedById, currentStatus, response}, (err) => {   
         if (err) {   
            console.log('couldnt update status’);   
         } else {   
            this.setState({isUpdated: true});   
         }   
      });   
   }    
   return {   
      loading: !this.state.isUpdated   
   }  
} `

**Comment by stubailo** [comment]
Are you sure this is related to the method? If you remove the method code does the error stop happening?

**Comment by itayb8** [comment]
yes, double checked, and the method is returning an error too

**Comment by stubailo** [comment]
>  the method is returning an error too

What error is it returning?

**Comment by stubailo** [comment]
Oh, the thing in the title. Can you paste the implementation of the method? The `run` method?

**Comment by itayb8** [comment]
`export const UpdateStatus = new ValidatedMethod({
  name: 'UpdateStatus',
  validate: null,
  run({changedById, currentStatus, response}:
    {changedById:string, currentStatus:ShipmentStationType, response:string}) 
    }
  }
});`

without the body of the method

**Comment by itayb8** [comment]
<img width="1280" alt="screen shot 2016-09-07 at 8 34 16 pm" src="https://cloud.githubusercontent.com/assets/17438255/18322257/8c6f4748-753a-11e6-8e6f-ca113742b58b.png">

**Comment by itayb8** [comment]
i console.log the err from the callback

**Comment by stubailo** [comment]
I think the problem is in the body of the method.

**Comment by itayb8** [comment]
Yes I checked it, thank you
