### ISSUE TITLE
Uncaught TypeError: Accounts.findUserByEmail is not a function(…) mdg_validated-method.js?hash=fb1c067…:119

### ISSUE THREAD

**Issue by neutron92** [meteor/validated-method#65]
`Uncaught TypeError: Accounts.findUserByEmail is not a function(…)  mdg_validated-method.js?hash=fb1c067…:119`

```
import {
  Accounts
} from 'meteor/accounts-base';

export const createschoolManager = new ValidatedMethod({
  name: 'users.create.schoolManager',
  validate: null,
  run(newUser) {
    console.log(Accounts);
    const existUser = Accounts.findUserByEmail(newUser.email);
    if (existUser) {
      return {
        "error": "User already uses this email to register"
      }
    }
    return Accounts.createUser({
      email: newUser.email,
      password: newUser.password,
      profile: {
        "profile.name": newUser.name,
        "profile.address": newUser.address,
      }
    });
  }
});
```

**Comment by mononeuroico** [comment]
Hi there,
I'm having the same problem. Any suggestions?
Thanks in advance

**Comment by mononeuroico** [comment]
I've just realised Accounts.findUserByEmail can only be run server side. So you need `if (Meteor.isServer`... somewhere.
Happy Christmas Eve!!

**Comment by pbatey** [comment]
If you have subscribed to users on the client, you can do this:

`Meteor.users.find({emails: { $elemMatch: { address: "example@example.com"}}})`

But it is case sensitive
