### ISSUE TITLE
How to wait for server method call to return respojse form server in client simulation

### ISSUE THREAD

**Issue by spiotr12** [meteor/validated-method#68]
Hello

Here is a problem:

I'm trying to call server `Meteor method` from `validated method`. The problem is that the client skips it (I think this is because it cannot find on the client) and do not wait for the method to return data - it behaves like the method does not exists so it returns `undefined`.

How do I write code so within validated method client simulation waits for server method to return data. The call back do not work.

e.g.:

```
run(invDoc){
	const tableId = Invitations.findOne({ _id: invDoc._id }).tableId;
	Meteor.call('isUniquePair', tableId, this.userId, function (err, res) {
		console.log('CALL RESPONSE', err, res);
		// server returns CALL RESPONSE undefined false
		// client returns CALL RESPONSE undefined undefined <- HERE IS THE PROBLEM
	});
}
```

I know if I would subscribe to required data it would work. Right now strictly on client I wait for `isUniquePair `method callback to return value and then I execute validated method. 

Is there any way to achieve this from validated method, so client simulation waits for server method call to return value?

Thanks for help! :)

**Comment by jasenkoh** [comment]
Wrapping that `Meteor.call` statement in `Promise.await` should to the trick, you can read more here https://goo.gl/UKBc2D

**Comment by spiotr12** [comment]
Thanks!
The way I did it was to actually user `Meteor.callPromise` from some package, I don't remember now.

**Comment by jasenkoh** [comment]
@spiotr12 here's an article that I wanted initially to share with you but somehow got confused in copy/paste, https://blog.meteor.com/using-promises-on-the-client-in-meteor-fb4f1c155f84#.bivbtmqes

I'm glad that you have it resolved

**Comment by nikhilgoswami** [comment]
I used future/fiber npm package https://github.com/jagi/meteor-astronomy/issues/562 very easy almost no change in function code is required only need to add try catch for it
