### ISSUE TITLE
Not compatible with fibers npm module

### ISSUE THREAD

**Issue by xvendo** [meteor/validated-method#78]
If you install the node package fibers and you also make use of validated-method your app will crash.

**Comment by hwillson** [comment]
@xvendo Can you provide a small runnable reproduction that shows this happening?

**Comment by xvendo** [comment]
@hwillson Fibers are automatically included in server builds and cannot be used on the client. I have used them in a method available for both environments "server" and "client". The validated-method builds stubs for "client" and "server". So the fibers get executed also on the client, which can't work. 

Basically It turns out It's not an incompatibility It's based on working with fibers on the wrong environment.

**Comment by hwillson** [comment]
Thanks for the update @xvendo. Sounds like we're okay to close this then.
