### ISSUE TITLE
Add support to Meteor v2.8+ callAsync

### ISSUE THREAD

**Issue by fracz** [meteor/validated-method#90]
I believe this package should add a feature to call `validatedMethod.callAsync` wit `Meteor.callAsync` introduced in [Meteor v2.8](https://guide.meteor.com/2.8-migration.html).

```js
// Method definition
const method = new ValidatedMethod({
  name, // DDP method name
  mixins, // Method extensions
  validate, // argument validation
  applyOptions, // options passed to Meteor.apply
  async run() {
   // Method body
  }
});

// Method call
method.callAsync({ arg1, arg2 });
```

Before it is introduced in the project, I came up with a simple mixin that uses [`applyAsync`](https://docs.meteor.com/api/methods.html#Meteor-applyAsync).

```js
const CallAsyncMixin = function (methodOptions) {
    methodOptions.callAsync = function (args) {
        return this.connection.applyAsync(this.name, [args], this.applyOptions);
    }
    return methodOptions;
}
```

Usage:

```js
const method = new ValidatedMethod({
  name, // DDP method name
  mixins: [CallAsyncMixin],
  validate, // argument validation
  applyOptions, // options passed to Meteor.apply
  async run() {
   // Method body
  }
});
```

**Comment by fracz** [comment]
After I started to use the mixin proposed above, I noticed a difference in behavior of `applyAsync` and `callAsync`, which I described on the Meteor forum: https://forums.meteor.com/t/different-results-of-callasync-and-applyasync/59335

Keep it in mind when using the proposed solution.

For now, I use the mixin below to have the correct stub behavior, but it ignores the `applyOptions` of the validated method.

```js
const CallAsyncMixin = function (methodOptions) {
    methodOptions.callAsync = function (args) {
        return this.connection.callAsync(this.name, args);
    }
    return methodOptions;
}
```

**Comment by Grubba27** [comment]
Nice mixin! 
I will close this issue as callAsync was added in 1.3.0, but If you want to make an issue to have a way to backport callAsync to other versions would be nice.
